### PR TITLE
removed -c term from bandpass function

### LINKED ISSUE #111: Adding the temporal mean image back?
In the code for removeNuisanceRegressor.sh, unless I am misinterpreting something, the temporal mean is added back to the detrended images from nuisance regression because "`# 3dTproject will demean (normalize)`". Yet, the code appears to compute this as `a + b - c`, where `a` is the detrended image, `b` is the temporal mean of the original image, and `c` is the temporal mean of the detrended image. If indeed 3dTproject demeans, why is it necessary to include the `- c` term at all?

      rm -rf "${outDir}"/tmp_bp* 2> /dev/null &&\
    	3dTproject -input "${inData}" -prefix "$outDir"/tmp_bp.nii.gz -mask "${mask}    " -bandpass "${fbot}" "${ftop}" -ort "${regressorsFile}" -verb &&\
      # add mean back in
    	3dTstat -mean -prefix "$outDir"/orig_mean.nii.gz "${inData}" &&\
    	3dTstat -mean -prefix "$outDir"/bp_mean.nii.gz "$outDir"/tmp_bp.nii.gz &&\
    	3dcalc -a "$outDir"/tmp_bp.nii.gz -b "$outDir"/orig_mean.nii.gz -c "$outDir"/bp_mean.nii.gz -expr "a+b-c" -prefix "${outDir}"/"$(basename "${inData%%.nii*}")"_bp_res4d.nii.gz

### PR DESCRIPTION
**Pull request by tbweng**
Fixes #111 .

Changes proposed in this pull request:
- removed the `- c` term after temporal filtering

### CODE REVIEW

File: removeNuisanceRegressor.sh [hunk 1]
```diff
@@ -154,7 +154,7 @@ function SimultBandpassNuisanceReg()
   # add mean back in
 	3dTstat -mean -prefix "$outDir"/orig_mean.nii.gz "${inData}" &&\
 	3dTstat -mean -prefix "$outDir"/bp_mean.nii.gz "$outDir"/tmp_bp.nii.gz &&\
```
Comment (jdkent) [inline removeNuisanceRegressor.sh]: Is this line still necessary? I don't believe we use `bp_mean.nii.gz` anywhere else.

**Review by jdkent — CHANGES_REQUESTED** [review]
if you delete the line I suggested, you will also need to modify [ds005_compcor.txt](https://github.com/HBClab/RestingState/blob/51acb672e7a8a9e75ca1e35d3b65ec0f57986fdb/.circleci/ds005_compcor.txt) and [ds005_compcor_global.txt](https://github.com/HBClab/RestingState/blob/51acb672e7a8a9e75ca1e35d3b65ec0f57986fdb/.circleci/ds005_compcor_global.txt) to remove the lines that contain`bp_mean.nii.gz` so that the tests pass.

Otherwise, LGTM.
